version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      # These should match the variables in your .env file, but point to the database service
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      PORT: 8080
    depends_on:
      - db
    # Optional: Mount your local code for easier development (hot-reloading)
    # volumes:
    #   - .:/usr/src/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: Expose database port for local access

volumes:
  postgres_data: